version: '3'
services:
  web:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    env_file: ../../.env
    restart: 'always'
    depends_on:
      - 'db'
    ports:
      - '${WEBSITE_PORT}:8080'
    environment:
      - 'DB_HOST=mongodb://${DB_USERNAME}:${DB_PASSWORD}@db:27017/mits?authSource=admin'
    command: ["./wait-for-it.sh", "db:27017", "--", "npm", "run", "start"]
  db:
    image: 'mongo:4.2'
    restart: 'always'
    volumes:
      - '${DB_DATA_PATH}/www:/data/db'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}'
